spring.application.name=foodCycle-backend

# Database connection
spring.datasource.url=jdbc:mysql://localhost:3306/foodCycle
spring.datasource.username=root
spring.datasource.password=admin@123
spring.jpa.hibernate.ddl-auto=update

